version: '3.8'

services:
  app:
    build: .
    container_name: bancolombiia_app
    ports:
      - "5008:5008"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
      - redis
    networks:
      - app_network
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_DATABASE=bancolombia
      - DB_USERNAME=root
      - DB_PASSWORD=Espumas2025*.
      - REDIS_HOST=redis
      - REDIS_PORT=6380

  db:
    image: mysql:8.0
    container_name: bancolombiia_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bancolombia
      MYSQL_ROOT_PASSWORD: Espumas2025*.
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3307:3307"
    command: 
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: bancolombiia_redis
    ports:
      - "6380:6380"
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge